name: movie_super
description: A new Flutter project.
# 
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
# -------------------------------------- dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.17.4
  fluro: ^2.0.3
  material: ^1.0.0+2
  wiredash: ^0.7.0+1
  flutter_statusbarcolor_ns: ^0.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
# -------------------------------------- dependencies
# -------------------------------------- set up assets
# LOGO
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

# FRONT AND IMAGES
flutter:
  uses-material-design: true
  # assets:
    # - images/logo-app.png
    # -
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/SawarabiMincho-Regular.ttf
  #       - asset: fonts/SawarabiMincho-Regular.ttf
  #         style: italic
  #   - family: Sawarabi Mincho Regular

